packages:
  - '.'
overrides:
  better-call: 1.3.7
  cookie: ^0.7.0
  '@esbuild-kit/core-utils>esbuild': ^0.25.0
ignoredBuiltDependencies:
  - '@prisma/client'
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
allowBuilds:
  '@prisma/client': false
  better-sqlite3: false
  esbuild: true
