name: Accessibility

on:
  pull_request:
    paths:
      - '.github/workflows/accessibility.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'apps/dashboard/**'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/accessibility.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'apps/dashboard/**'
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/setup@4700d737c3d7a2e7199f3d42a920f0bf7f34e411 # v2.0.1
        with:
          runtime: node@lts
          cache: true
          install: false
      - run: pnpm install --frozen-lockfile
      - name: Run Accessibility Audit
        run: pnpm run test:accessibility:ci
